name: Markdown lint
on:
  pull_request:
    paths:
      - '**/*.md'
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '.github/workflows/markdownlint.yml'
      - '.markdownlint.jsonc'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md
          config: .markdownlint.jsonc
