name: PR checks
on:
  pull_request:
    paths:
      - 'designs/**.md'
      - 'general-questions/**.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic validation
        run: |
          set -e
          base="${{ github.base_ref }}"
          CHANGED=$(git diff --name-only origin/$base...HEAD | grep -E '^(designs|general-questions)/.*\.md$' || true)
          [ -z "$CHANGED" ] && echo "No new/changed files in designs/ or general-questions/." && exit 0
          echo "$CHANGED" | while read -r f; do
            b=$(basename "$f")
            echo "$b" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}-' || { echo "❌ $f: filename must start with YYYY-MM-DD-"; exit 1; }
            grep -qE '^# ' "$f" || echo "⚠️  $f: consider adding a top-level '# ' title"
          done
