name: Basic PR check
on:
  pull_request:
    paths:
      - 'designs/**.md'
      - 'general-questions/**.md'

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Check filenames and titles
        run: |
          set -e
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.event.pull_request.head.sha }}"
          CHANGED=$(git diff --name-only "$base" "$head" | grep -E '^(designs|general-questions)/.*\.md$' || true)
          [ -z "$CHANGED" ] && echo "No relevant changes." && exit 0
          for f in $CHANGED; do
            b=$(basename "$f")
            echo "Checking $f"
            echo "$b" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}-' \
              || { echo "❌ $f: filename must start with YYYY-MM-DD-"; exit 1; }
            grep -qE '^# ' "$f" \
              || { echo "❌ $f: add a top-level '# ' title"; exit 1; }
          done
